### ISSUE TITLE
Unsupported HTTP version

### ISSUE THREAD

**Issue by mweinelt** [RealDolos/volapi#11]
I'm trying out the example in your README and only end up with:

> dropping connection to peer tcp4:137.74.42.196:443 with abort=True: Unsupported HTTP version ('HTTP/1.0')

The messages comes from the autobahn python package.

**Comment by szero** [comment]
Ugh, its one of those "works one my machine" moments. From this laconic error message I can only shoot out some guesses like, your SSL/TLS system library is out of date. If you're Mac user you can probably update it with homebrew.

**Comment by mweinelt** [comment]
Not quite a Mac though. What else do you need? I can reproduce this on NixOS, Archlinux and Debian.

```sh
$ uname -a
Linux gaia 5.1.6 #1-NixOS SMP Fri May 31 13:43:59 UTC 2019 x86_64 GNU/Linux
```

```sh
$ openssl version
OpenSSL 1.0.2r  26 Feb 2019
$ python --version
Python 3.7.3
$ pip freeze
asn1crypto==0.24.0
autobahn==19.6.2
certifi==2019.3.9
cffi==1.12.3
chardet==3.0.4
cryptography==2.7
idna==2.8
pycparser==2.19
requests==2.22.0
six==1.12.0
txaio==18.8.1
urllib3==1.25.3
virtualenv==16.4.1
volapi==5.15.0
```

**Comment by mweinelt** [comment]
It broke somewhere between https://github.com/crossbario/autobahn-python/releases/tag/19.3.3 and https://github.com/crossbario/autobahn-python/releases/tag/v19.5.1.

Downgrading autobahn helps.
