### ISSUE TITLE
Unhandled Socket Message Type

### ISSUE THREAD

**Issue by kadranel** [RealDolos/volapi#14]
I guess there has been a new type of message that should somehow be handled by the API: 'removeMessages'. I guess mods can delete messages now?
Anyways, currently it produces the following warning:

> /usr/local/lib/python3.7/site-packages/volapi/handler.py:81: Warning: unknown data type 'removeMessages' with data '{'msgIds': ['lCOXlK4YeY4bZKHiHyqIzP5np5BPK/uKF5BG9219jvU=']}'
>   warnings.warn(f"unknown data type '{target}' with data '{data}'", Warning)

This isn't really something critical, just something to consider for the next revision. 
Best regards, kad

**Comment by szero** [comment]
Yea there is removeMessages command, but its mod-only as of now. This is just information on what messages were removed, I imagine this is quite useless for bot users, but you could check up what is being removed by listening to 'chat' event and matching the ids from removeMessages with whats in the 'data.id' attribute of chat instance.

**Comment by kadranel** [comment]
Aaah, no i was not really wanting to use it anyway. This issue is more a proposal to add "removeMessages" to handler.py as a generic or as a singular method, if you really want to support this further in order to get rid of the constant warnings in the console.  The following implementation basically achieves this and would allow API users to listen for removeMessages if they really want to do it. 
Just consider this as an addition for when you want to release a new version of volapi. 
```python
GENERICS = [
    "roomScore",
    "submitChat",
    "submitCommand",
    "pro",
    "room_old",
    "upload",
    "reconnectTimeout",
    "removeMessages",
]
```
(Line 13 of handler.py)

**Comment by szero** [comment]
I did done it over here: b4adb94
