### ISSUE TITLE
Problem with installing 5.19.0

### ISSUE THREAD

**Issue by kadranel** [RealDolos/volapi#15]
Installing volapi 5.19.0 via pip on python3.8 and python3.7 gets me the following error and subsequently does not install:

ERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.
volapi depends on python-engineio@ git+https://github.com/szero/python-engineio

After having looked at your current code i don't even comprehend where this dependency is coming from, so maybe you can help me out with understanding that.

**Comment by szero** [comment]
Yea, this is strange, I was doing some stuff in other branch and had that dependency in requirementx.txt but it wasn't even added to git index so not sure how it have landed on PYPI. Will do minor vola update to fix this now.

**Comment by szero** [comment]
Try installing it from pypi now, @kadranel. Fixes in 9353134 commit
