### ISSUE TITLE
Problems with selected autobahn version in Python 3.8

### ISSUE THREAD

**Issue by kadranel** [RealDolos/volapi#16]
(First of all thanks for your fix yesterday ;) )

Apart from that: Using the autobahn version defined in requirements.txt (autobahn==19.3.3) is not possible with python 3.8 due to the following error: AttributeError: module 'time' has no attribute 'clock'

For more reference on this refer to the following in [What’s New In Python 3.8](https://docs.python.org/3/whatsnew/3.8.html): 
`The function time.clock() has been removed, after having been deprecated since Python 3.3: use time.perf_counter() or time.process_time() instead, depending on your requirements, to have well-defined behavior. (Contributed by Matthias Bussonnier in bpo-36895.)`

Upgrading autobahn to the current version on pip (20.7.1) fixes this problem. (See: https://github.com/crossbario/autobahn-python/pull/1259) Sadly i don't know the exact reasons why autobahn was pinned to 19.3.3 so I can not tell you if it will be compatible with whatever created that fixed requirement in the first place.

**Comment by szero** [comment]
It was pinned because of this https://github.com/volafiled/python-volapi/issues/11, I will change autobahn version since stuff is broken anyways. Btw, I have python ver 3.8.6rc1 and it doesn't error out for me.

**Comment by kadranel** [comment]
After having read more about it this comes from the fact, that the part of the code that uses time.clock in autobahn 19.3.3 is only accessed on Windows. On my Linux VM it works as well. I guess this fact is part of why the function was removed in Python 3.8

So i don't necessarily care about a fix of this, but it may be better to just try the more modern version of autobahn to not get every Windows user excluded in python 3.8

**Comment by szero** [comment]
Fixed with the commit above!
