### ISSUE TITLE
Deleting files while not logged in silently fails

### ISSUE THREAD

**Issue by cfranklin42** [RealDolos/volapi#17]
Calling file.delete() silently fails if you aren't logged in. If possible it should raise an exception if you aren't logged in, or if there's a server response an exception could be raised if the response indicates failure.

**Comment by szero** [comment]
Hello, made some fixes in this commit https://github.com/volafiled/python-volapi/commit/8eaad3937382496a4593f176d299b877cc32e100 regarding this issue, let me know if its fine now.
