### ISSUE TITLE
orjson is not available for my system, could not a different json library be used?

### ISSUE THREAD

**Issue by anoduck** [RealDolos/volapi#18]
I want to write a simple file scraper for open volafile rooms, one that employs the use of requests and the api, rather than being dependent on chromedriver as most available currently are. Unfortunately, I can't get orjson installed on my machine, since it involves python attempting to compile needed libraries from rust via the cc compiler automatically, and OpenBSD possesses both gcc and clang. For OpenBSD, the C compiler needs to be designated, which is difficult to do when your installing a python package and environment variables are not picked up. The library itself is rather obtuse in size and requires lots of dependencies, yet is only used in two of the source code files, and I don't see a benefit in using orjson over the numerous other json libraries available for python. In short, it appears to be overkill. 

Is there anyway a different json library could be employed, one that is native to python?

**Comment by szero** [comment]
I was thinking about it after reading [this](https://lwn.net/Articles/845535/) article. Will release version of this lib where stock json module is the default with an option to install it with orjson with extra pip argument.

**Comment by anoduck** [comment]
Fascinating article, I much enjoyed reading it. It explains many of the difficulties I have experienced. I primarily run OpenBSD and Alpine on my systems, so this article is right up my alley since I am doubly affected. I also like rust, and although I am a novice programmer at best, I will try to pick up what I can in order to learn how to program with it. 

Will be looking forward to the next release! Cheers, and thanks!

**Comment by szero** [comment]
You can try new release, @anoduck, it should install without `orjson` by default now.

**Comment by anoduck** [comment]
AND boom goes the dynamite! I am so excited. Installed without a hitch, time to get busy now. Thanks for working with me, it was a very informative exchange.

**Comment by anoduck** [comment]
@szero I am truly indebted to you, because I don't think you could have made life any easier when you provided the example for acquiring urls via the api. That makes writing a simple script to download those files as stupid simple, and that is very much a good thing. Thanks for working with me, it has been a pleasure. 

```python
from volapi import Room

with Room("BEEPi", "ScrappyBoy") as BEEPi:
    BEEPi.listen(once=True)
    for f in BEEPi.files:
        print(f.url)
        img_url = f.url
        img_num = str(randint(1, 9999))
        img_name = rid + img_num + ".jpg"
        with requests.get(img_url, stream=True, allow_redirects=True) as r:
          with open(img_name, "wb") as p:
            r.raw.decode_content = True
            shutil.copyfileobj(r.raw, p)
```

**Comment by szero** [comment]
Ye some docs would be helpful for this thing, Room class in volapi.py file, User class in user.py and ChatMessage class in user.py (instances of ChatMessage class are returned by `chat` event) file contains properties and methods you would want to use in a script (functions are commented for the most part). handler.py file specifies what events we can listen for with the add_listener method of Room class (all event names are in the calls of enqueue_data method in handler.py file).

**Comment by anoduck** [comment]
It is a well written api, and makes life quite easy to access volafile features programmatically. It was a breeze writing my simplistic script. I posted it here for now: [vola-scrape](https://gist.github.com/anoduck/e63e46201f4e348fbc5658ef34efa896). 

I just have not quite figured out how to get argparse to pass the room_id variable to the scrape function. It is such a newb mistake, I know.
