### ISSUE TITLE
this is not volapi-neo

### ISSUE THREAD

**Issue by ghost** [RealDolos/volapi#5]
delete this repository immediately and contribute to NEO instead!

**Comment by dongmaster** [comment]
Volapi-neo is the pinnacle of trash.
Accept Volapi as your lord and saviour.
Discover salvation and embrace the gospel of V O L A P I.

**Comment by RealDolos** [comment]
Reopening just so I can close it again...

**Comment by RealDolos** [comment]
Daniel, pls leave
